version: '3.2'
services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    volumes:
      - ./:/var/www/app
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge